name: Mausam CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14"

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t mausam .

    - name: Test Docker container
      run: docker run -d -p 5000:5000 mausam

    - name: Deploy to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker tag mausam ${DOCKER_USERNAME}/mausam:latest
        docker push ${DOCKER_USERNAME}/mausam:latest
